# 個人用設定 - テストよりも優先度は高い
debug: false
env:
  otlp:
    enabled: false
      
logging.level:
  org.springframework: INFO

rms:
  debug:
    configdump:
      enable: false
      #system-properties: true
      #system-environment: true
