env:
  otlp:
    enabled: true
    endpoint:
      scheme: http
      host: localhost
      port-rest: 4318
      port-grpc: 4317

logging.level:
  org.springframework: info
    #transaction: info
    #security: trace
    #context.support.ResourceBundleMessageSource: DEBUG
  io.extact: debug

spring:
  application:
    name: rms-console-remote
  messages:
    basename: fw-messages,application-messages
    encoding: UTF-8

server:
  port: 9080 # for actuator

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env,beans"
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
      group:
        readiness:
          include: "readinessState,db,dependentServers"
      validate-group-membership: false # groupにindicatorが存在しない場合もエラーにしない設定

  # =======
  # ＜TelemetryパイプラインはOTEL+HTTPの標準的な構成＞
  # metrics(micrometer-registry-otlp) ------------(HTTP)--┐                ┌-- (http://prometheus:9090/api/v1/otlp) -> Prometheus/otlp-receiver
  # tracing(micrometer-tracing-bridge-otel) ------(gRPC)--├--> collector --┤-- (http://tempo:4418) ------------------> Grafana Tempo
  # logging(opentelemetry-logback-appender-1.0) --(gRPC)--┘                └-- (http://loki:3100/otlp) --------------> Grafana Loki
  # =======
  metrics:
    tags:
      application: ${spring.application.name}
      instance: "host.docker.internal:8080"
    distribution:
      percentiles-histogram:
        http.server.requests: true
  tracing:
    sampling:
      probability: 1.0  # 100%サンプリング（開発環境向け）
  otlp:
    metrics:
      export:
        enabled: ${env.otlp.enabled}
        url: ${env.otlp.endpoint.scheme}://${env.otlp.endpoint.host}:${env.otlp.endpoint.port-rest}/v1/metrics # MicrometerはgRPCは未サポート
        step: 2s
    tracing:
      export:
        enabled: ${env.otlp.enabled}
      transport: grpc
      endpoint: ${env.otlp.endpoint.scheme}://${env.otlp.endpoint.host}:${env.otlp.endpoint.port-grpc} # for gRPC
    logging:
      export:
        enabled: ${env.otlp.enabled}
      transport: grpc
      endpoint: ${env.otlp.endpoint.scheme}://${env.otlp.endpoint.host}:${env.otlp.endpoint.port-grpc} # for gRPC
      
      
rms:
  debug:
    configdump:
      enable: true # change to true in the test class
      #system-properties: on
      #system-environment: on
  application:
    url: http://localhost:8080
    format:
      date: yyyyMMdd
      date-time: yyyyMMdd HH:mm
  health:
    depend-services:
      - ${rms.applicaiton.url}/actuator/health/readiness
