spring:
  application:
    name: rms-console-remote
  messages:
    basename: fw-messages,application-messages
    encoding: UTF-8

server:
  port: 9080 # for actuator

rms:
  log:
    access:
      enable: false # for actuator
  application:
    url: http://localhost:8080
    format:
      date: yyyyMMdd
      date-time: yyyyMMdd HH:mm
  health:
    depend-services:
      - ${rms.applicaiton.url}/actuator/health/readiness
