env:
  otlp:
    enabled: true

logging.level:
  org.springframework: info
    #transaction: info
    #security: trace
    #context.support.ResourceBundleMessageSource: DEBUG
  io.extact: debug

spring:
  application:
    name: rms-console-remote
  messages:
    basename: fw-messages,application-messages
    encoding: UTF-8

server:
  port: 9080 # for actuator

rms:
  log:
    access:
      enable: false
  debug:
    configdump:
      enable: true # change to true in the test class
      #system-properties: on
      #system-environment: on
  application:
    url: http://localhost:8080
    format:
      date: yyyyMMdd
      date-time: yyyyMMdd HH:mm
  health:
    depend-services:
      - ${rms.applicaiton.url}/actuator/health/readiness
