<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>io.extact</groupId>
        <artifactId>msa-spring-rms-ui-console</artifactId>
        <version>0.0.1-SNAPSHOT</version>
        <relativePath>../pom.xml</relativePath>
    </parent>
    <artifactId>msa-spring-rms-ui-console-core</artifactId>
    <packaging>jar</packaging>
    <name>msa-spring-rms-ui-console-core</name>

    <dependencies>

        <!-- ======================================== -->
        <!-- adding optional transitive dependencies  -->
        <!-- ======================================== -->
        <dependency>
            <groupId>io.extact</groupId>
            <artifactId>msa-spring-platform-core</artifactId>
        </dependency>
        <dependency>
            <groupId>io.extact</groupId>
            <artifactId>msa-spring-platform-fw</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.security</groupId>
            <artifactId>spring-security-core</artifactId>
        </dependency>

        <!-- ========================================= -->
        <!-- application-specific dependencies         -->
        <!-- ========================================= -->
        <dependency>
            <groupId>org.beryx</groupId>
            <artifactId>text-io</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>

        <!-- Metrics for OTLP -->
        <dependency>
            <groupId>io.micrometer</groupId>
            <artifactId>micrometer-registry-otlp</artifactId>
        </dependency>
        <!-- Tracing for OTLP -->
        <dependency>
            <groupId>io.micrometer</groupId>
            <artifactId>micrometer-tracing-bridge-otel</artifactId>
        </dependency>
        <dependency>
            <groupId>net.ttddyy.observation</groupId>
            <artifactId>datasource-micrometer-spring-boot</artifactId>
            <version>1.1.2</version>
        </dependency>
        <!-- Logging for OTLP -->
        <dependency>
            <groupId>io.opentelemetry.instrumentation</groupId>
            <artifactId>opentelemetry-logback-appender-1.0</artifactId>
            <version>2.15.0-alpha</version>
        </dependency>
        <!-- Exporter for OTLP  -->
        <dependency>
            <groupId>io.opentelemetry</groupId>
            <artifactId>opentelemetry-exporter-otlp</artifactId>
        </dependency>


    </dependencies>

</project>
